@startuml
package presentation{
    class Controller
    class Form
}

package usecase{
    class Service
    class Dto
}

package domain {
    package auth {
        class TodoUser
    }
    package todo {
        class Todo
    }
    interface Repository
}

package infrastructure{
    class RepositoryImpl
    interface Mapper
    class Entity
}

presentation --> usecase
usecase --> domain
domain <-- infrastructure

Controller -> Form
Controller --> Service
Controller --> Dto
Service --> Todo
Service --> Repository
Repository <|.. RepositoryImpl
RepositoryImpl --> Mapper
RepositoryImpl -> Entity


@enduml
